name: SpeedBuilders2
version: '${version}'
main: com.hermitblaze.speedbuilders.SpeedBuildersPlugin
api-version: '1.20'
description: SpeedBuilders 2 - memoriza y replica construcciones.
authors: [hermitblaze1377]

commands:
  speedbuilders:
    description: Comando principal de SpeedBuilders 2.
    aliases: [sb]
    usage: /<command> ayuda

permissions:
  speedbuilders.jugar:
    description: Permite unirse y salir de las partidas.
    default: true
  speedbuilders.admin:
    description: Permite configurar y administrar el minijuego.
    default: op
